name=DA DNSSEC Sync Manager
id=da_dnssec_sync_manager
author=TLWebdesign
version=3.0.0
active=yes
admin_run_as=diradmin
reseller_run_as=diradmin
installed=yes
update_url=https://raw.githubusercontent.com/TLWebdesignNL/DA-DNSSEC-SYNC-MANAGER/refs/heads/main/da_dnssec_sync_manager.tar.gz
version_url=https://raw.githubusercontent.com/TLWebdesignNL/DA-DNSSEC-SYNC-MANAGER/refs/heads/main/version.html
